[workspace]
authors = ["yuyu_wsl <yx.shuai@stu.xidian.edu.cn>"]
channels = ["conda-forge"]
name = "LaserTran_Simulate"
platforms = ["linux-64",'win-64']
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13,<3.14"
numpy = ">=2.4.0,<3"
scipy = ">=1.16.3,<2"
scipy-stubs = ">=1.16.3.3,<2"
pandas = ">=2.3.3,<3"
matplotlib = ">=3.10.8,<4"
ipython = ">=9.9.0,<10"
jupyter = ">=1.1.1,<2"
pyvista = ">=0.46.4"
trame = ">=3.12.0,<4"
trame-vtk = ">=2.10.2,<3"
trame-vuetify = ">=3.2.0,<4"
